package core.view;

import core.controllers.utils.Response;
import core.controllers.utils.Status;
import core.controllers.doctor.DoctorController;
import core.controllers.doctor.IDoctorController;
import core.controllers.patient.PatientController;
import core.controllers.patient.IPatientController;
import core.observer.Observer;
import core.observer.EventType;
import core.models.storage.IStorage;

import java.awt.Color;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

public class AdminView extends javax.swing.JFrame implements Observer {

    private int x, y;
    private final IStorage database;
    private final IDoctorController doctorController;
    private final IPatientController patientController;
    private final long adminId;

    public AdminView(IStorage database, long adminId) {
        this.database = database;
        this.adminId = adminId;
        this.doctorController = new DoctorController(database);
        this.patientController = new PatientController(database);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        database.addObserver(this);
        refreshComboBoxes();
    }

    @Override
    public void update(EventType event, Object data) {
        if (event == EventType.USER_ADDED || event == EventType.USER_UPDATED) {
            refreshComboBoxes();
        }
    }

    @SuppressWarnings("unchecked")
    private void refreshComboBoxes() {
        cmbSelectUser.removeAllItems();
        cmbSelectUser.addItem("Select one");

        cmbSelectUserSecondary.removeAllItems();
        cmbSelectUserSecondary.addItem("Select one");

        Response docResp = patientController.getDoctorList();
        if (docResp.getStatus() == Status.OK && docResp.getData() instanceof List) {
            for (Map<String, String> d : (List<Map<String, String>>) docResp.getData()) {
                cmbSelectUser.addItem(d.get("id"));
            }
        }

        Response patResp = doctorController.getPatientList();
        if (patResp.getStatus() == Status.OK && patResp.getData() instanceof List) {
            for (Map<String, String> p : (List<Map<String, String>>) patResp.getData()) {
                cmbSelectUserSecondary.addItem(p.get("id"));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new core.view.PanelRound();
        panelRound2 = new core.view.PanelRound();
        btnClose = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        panelRound3 = new core.view.PanelRound();
        btnGoToDoctorView = new javax.swing.JButton();
        btnGoToPatientView = new javax.swing.JButton();
        lblDocFirstname = new javax.swing.JLabel();
        txtDocFirstname = new javax.swing.JTextField();
        lblDocLastname = new javax.swing.JLabel();
        txtDocLastname = new javax.swing.JTextField();
        lblDocId = new javax.swing.JLabel();
        txtDocId = new javax.swing.JTextField();
        lblDocSpecialty = new javax.swing.JLabel();
        lblDocLicense = new javax.swing.JLabel();
        txtDocLicense = new javax.swing.JTextField();
        lblDocOffice = new javax.swing.JLabel();
        txtDocOffice = new javax.swing.JTextField();
        lblDocUser = new javax.swing.JLabel();
        txtDocUsername = new javax.swing.JTextField();
        lblDocPassword = new javax.swing.JLabel();
        txtDocPassword = new javax.swing.JTextField();
        lblDocConfirmPass = new javax.swing.JLabel();
        txtDocConfirmPass = new javax.swing.JTextField();
        cmbDocSpecialty = new javax.swing.JComboBox<>();
        btnRegisterDoctor = new javax.swing.JButton();
        sepVertical1 = new javax.swing.JSeparator();
        cmbSelectUser = new javax.swing.JComboBox<>();
        lblDoctorSection = new javax.swing.JLabel();
        lblPatientSection = new javax.swing.JLabel();
        cmbSelectUserSecondary = new javax.swing.JComboBox<>();
        sepVertical2 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setRadius(50);

        panelRound2.setRadius(50);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblTitle.setText("ADMIN VIEW");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle))
        );

        btnGoToDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnGoToDoctorView.setText("DOCTOR VIEW");
        btnGoToDoctorView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToDoctorViewActionPerformed(evt);
            }
        });

        btnGoToPatientView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnGoToPatientView.setText("PATIENT VIEW");
        btnGoToPatientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToPatientViewActionPerformed(evt);
            }
        });

        lblDocFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocFirstname.setText("Firstname");

        txtDocFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocLastname.setText("Lastname");

        txtDocLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocId.setText("ID");

        txtDocId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocSpecialty.setText("Specialty");

        lblDocLicense.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocLicense.setText("License Number");

        txtDocLicense.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocOffice.setText("Assigned office");

        txtDocOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocUser.setText("User");

        txtDocUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocPassword.setText("Password");

        txtDocPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocConfirmPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocConfirmPass.setText("Password confirmation");

        txtDocConfirmPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbDocSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbDocSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnRegisterDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegisterDoctor.setText("Save");
        btnRegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDoctorActionPerformed(evt);
            }
        });

        sepVertical1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cmbSelectUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbSelectUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblDoctorSection.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorSection.setText("Doctor");

        lblPatientSection.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientSection.setText("Patient");

        cmbSelectUserSecondary.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbSelectUserSecondary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        sepVertical2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnRegisterDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDocFirstname)
                                    .addComponent(lblDocSpecialty))
                                .addGap(18, 18, 18)
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(cmbDocSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDocLicense)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(txtDocFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lblDocLastname)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDocId)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(lblDocOffice)
                                .addGap(18, 18, 18)
                                .addComponent(txtDocOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(lblDocUser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDocUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(lblDocPassword)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDocPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(lblDocConfirmPass)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(333, 333, 333)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGoToDoctorView)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(cmbSelectUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(lblDoctorSection)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(318, 318, 318)))
                .addComponent(sepVertical1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGoToPatientView)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(cmbSelectUserSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblPatientSection)))
                .addGap(88, 88, 88))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(sepVertical2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(sepVertical1)
                .addContainerGap())
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocFirstname)
                    .addComponent(txtDocFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocLastname)
                    .addComponent(txtDocLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocId)
                    .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocSpecialty)
                    .addComponent(cmbDocSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocLicense)
                    .addComponent(txtDocLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDocOffice)
                    .addComponent(txtDocOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocUser)
                            .addComponent(txtDocUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocPassword)
                            .addComponent(txtDocPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocConfirmPass)
                            .addComponent(txtDocConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblDoctorSection)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSelectUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnGoToDoctorView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnRegisterDoctor)
                .addGap(123, 123, 123)
                .addComponent(btnLogout)
                .addGap(38, 38, 38))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblPatientSection)
                .addGap(18, 18, 18)
                .addComponent(cmbSelectUserSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnGoToPatientView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sepVertical2)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterDoctorActionPerformed
        String firstname = txtDocFirstname.getText();
        String lastname = txtDocLastname.getText();
        String idStr = txtDocId.getText();
        String spec = cmbDocSpecialty.getItemAt(cmbDocSpecialty.getSelectedIndex());
        String licenseNumber = txtDocLicense.getText();
        String assignedOffice = txtDocOffice.getText();
        String username = txtDocUsername.getText();
        String password = txtDocPassword.getText();
        String comPassword = txtDocConfirmPass.getText();
        
        Response response = doctorController.registerDoctor(
            idStr, username, firstname, lastname,
            password, comPassword, spec, licenseNumber, assignedOffice
        );
        
        if (response.getStatus() == Status.OK) {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
            txtDocFirstname.setText(""); txtDocLastname.setText(""); txtDocId.setText("");
            txtDocLicense.setText(""); txtDocOffice.setText(""); txtDocUsername.setText("");
            txtDocPassword.setText(""); txtDocConfirmPass.setText("");
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterDoctorActionPerformed

    private void btnGoToDoctorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToDoctorViewActionPerformed
        if (cmbSelectUser.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long selectedId = Long.parseLong(cmbSelectUser.getItemAt(cmbSelectUser.getSelectedIndex()));
        Response resp = doctorController.getDoctorData(selectedId);
        if (resp.getStatus() == Status.OK) {
            DoctorView doctor = new DoctorView(database, adminId, selectedId, true);
            database.removeObserver(this);
            this.dispose();
            doctor.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "El usuario seleccionado no es un Doctor.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGoToDoctorViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginView login = new LoginView(database);
        database.removeObserver(this);
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnGoToPatientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToPatientViewActionPerformed
        if (cmbSelectUserSecondary.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long selectedId = Long.parseLong(cmbSelectUserSecondary.getItemAt(cmbSelectUserSecondary.getSelectedIndex()));
        Response resp = patientController.getPatientData(selectedId);
        if (resp.getStatus() == Status.OK) {
            PatientView patient = new PatientView(database, adminId, selectedId, true);
            database.removeObserver(this);
            this.dispose();
            patient.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "El usuario seleccionado no es un Paciente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGoToPatientViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnGoToDoctorView;
    private javax.swing.JButton btnGoToPatientView;
    private javax.swing.JButton btnRegisterDoctor;
    private javax.swing.JComboBox<String> cmbDocSpecialty;
    private javax.swing.JComboBox<String> cmbSelectUser;
    private javax.swing.JComboBox<String> cmbSelectUserSecondary;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblDocUser;
    private javax.swing.JLabel lblDocPassword;
    private javax.swing.JLabel lblDocConfirmPass;
    private javax.swing.JLabel lblDoctorSection;
    private javax.swing.JLabel lblPatientSection;
    private javax.swing.JLabel lblDocFirstname;
    private javax.swing.JLabel lblDocLastname;
    private javax.swing.JLabel lblDocId;
    private javax.swing.JLabel lblDocSpecialty;
    private javax.swing.JLabel lblDocLicense;
    private javax.swing.JLabel lblDocOffice;
    private javax.swing.JSeparator sepVertical1;
    private javax.swing.JSeparator sepVertical2;
    private javax.swing.JTextField txtDocConfirmPass;
    private javax.swing.JTextField txtDocFirstname;
    private javax.swing.JTextField txtDocLastname;
    private javax.swing.JTextField txtDocId;
    private javax.swing.JTextField txtDocLicense;
    private javax.swing.JTextField txtDocOffice;
    private javax.swing.JTextField txtDocUsername;
    private javax.swing.JTextField txtDocPassword;
    private core.view.PanelRound panelRound1;
    private core.view.PanelRound panelRound2;
    private core.view.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}


