/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.view;

import core.controllers.utils.Response;
import core.controllers.utils.Status;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import core.models.storage.IStorage;
import core.controllers.login.LoginController;
import core.controllers.login.ILoginController;
import core.controllers.patient.PatientController;
import core.controllers.patient.IPatientController;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LoginView extends javax.swing.JFrame {

    private int x, y;
    private final IStorage database;
    private final ILoginController loginController;
    private final IPatientController patientController;

    public LoginView(IStorage database) {
        this.database = database;
        this.loginController = new LoginController(database);
        this.patientController = new PatientController(database);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new core.view.PanelRound();
        panelRound2 = new core.view.PanelRound();
        btnClose = new javax.swing.JButton();
        tabsMain = new javax.swing.JTabbedPane();
        panelRound3 = new core.view.PanelRound();
        lblLoginTitle = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        panelRegister = new javax.swing.JPanel();
        lblRegFirstname = new javax.swing.JLabel();
        txtRegFirstname = new javax.swing.JTextField();
        lblRegLastname = new javax.swing.JLabel();
        txtRegLastname = new javax.swing.JTextField();
        lblRegId = new javax.swing.JLabel();
        txtRegId = new javax.swing.JTextField();
        lblRegGender = new javax.swing.JLabel();
        lblRegPhone = new javax.swing.JLabel();
        txtRegPhone = new javax.swing.JTextField();
        lblRegEmail = new javax.swing.JLabel();
        txtRegEmail = new javax.swing.JTextField();
        lblRegUser = new javax.swing.JLabel();
        txtRegUsername = new javax.swing.JTextField();
        txtRegPassword = new javax.swing.JTextField();
        lblRegPassword = new javax.swing.JLabel();
        lblRegConfirmPass = new javax.swing.JLabel();
        txtRegConfirmPass = new javax.swing.JTextField();
        cmbRegGender = new javax.swing.JComboBox<>();
        btnRegisterPatient = new javax.swing.JButton();
        lblRegAddress = new javax.swing.JLabel();
        txtRegAddress = new javax.swing.JTextField();
        lblRegBirthdate = new javax.swing.JLabel();
        txtRegBirthdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setRadius(50);

        panelRound2.setRadius(50);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblLoginTitle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblLoginTitle.setText("LOGIN");

        txtLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginUsername.setText("USERNAME");

        txtLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginPassword.setText("PASSWORD");

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogin.setText("ENTER");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(lblLoginTitle)
                .addGap(481, 481, 481))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoginPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblLoginTitle)
                .addGap(74, 74, 74)
                .addComponent(lblLoginUsername)
                .addGap(18, 18, 18)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginPassword)
                .addGap(18, 18, 18)
                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLogin)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tabsMain.addTab("Login", panelRound3);

        lblRegFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegFirstname.setText("Firstname");

        txtRegFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegLastname.setText("Lastname");

        txtRegLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegId.setText("ID");

        txtRegId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegGender.setText("Gender");

        lblRegPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegPhone.setText("Phone");

        txtRegPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegEmail.setText("Email");

        txtRegEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegUser.setText("User");

        txtRegUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtRegPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegPassword.setText("Password");

        lblRegConfirmPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegConfirmPass.setText("Password confirmation");

        txtRegConfirmPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRegConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegConfirmPassActionPerformed(evt);
            }
        });

        cmbRegGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbRegGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        btnRegisterPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegisterPatient.setText("Save");
        btnRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPatientActionPerformed(evt);
            }
        });

        lblRegAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegAddress.setText("Address");

        txtRegAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegBirthdate.setText("Birthdate");

        txtRegBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelRegisterLayout = new javax.swing.GroupLayout(panelRegister);
        panelRegister.setLayout(panelRegisterLayout);
        panelRegisterLayout.setHorizontalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblRegPassword))
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(lblRegUser))
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(txtRegConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(btnRegisterPatient))
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblRegConfirmPass))
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelRegisterLayout.createSequentialGroup()
                                .addComponent(lblRegBirthdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRegBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRegisterLayout.createSequentialGroup()
                                .addComponent(lblRegFirstname)
                                .addGap(34, 34, 34)
                                .addComponent(txtRegFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegLastname)
                            .addComponent(lblRegAddress))
                        .addGap(18, 18, 18)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRegisterLayout.createSequentialGroup()
                                .addComponent(txtRegLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegId)
                                .addGap(30, 30, 30)
                                .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegGender)
                                .addGap(26, 26, 26)
                                .addComponent(cmbRegGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRegisterLayout.createSequentialGroup()
                                .addComponent(txtRegAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegPhone)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRegEmail)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panelRegisterLayout.setVerticalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegFirstname)
                    .addComponent(txtRegFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegLastname)
                    .addComponent(txtRegLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegId)
                    .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegGender)
                    .addComponent(cmbRegGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegBirthdate)
                        .addComponent(txtRegBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegAddress)
                        .addComponent(txtRegAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegPhone)
                        .addComponent(txtRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegEmail)
                        .addComponent(txtRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lblRegUser)
                .addGap(18, 18, 18)
                .addComponent(txtRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegPassword)
                .addGap(18, 18, 18)
                .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegConfirmPass)
                .addGap(18, 18, 18)
                .addComponent(txtRegConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRegisterPatient)
                .addGap(42, 42, 42))
        );

        tabsMain.addTab("Patient register", panelRegister);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(tabsMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabsMain)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtLoginUsername.getText().trim();
        String password = txtLoginPassword.getText().trim();
        
        Response response = loginController.login(username, password);
        
        if (response.getStatus() != Status.OK) {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        @SuppressWarnings("unchecked")
        Map<String, String> userData = (Map<String, String>) response.getData();
        long userId = Long.parseLong(userData.get("id"));
        String role = userData.getOrDefault("type", "");
        
        if ("admin".equals(role)) {
            AdminView admin = new AdminView(database, userId);
            this.dispose();
            admin.setVisible(true);
        } else if ("doctor".equals(role)) {
            DoctorView doctor = new DoctorView(database, userId, userId, false);
            this.dispose();
            doctor.setVisible(true);
        } else {
            PatientView patient = new PatientView(database, userId, userId, false);
            this.dispose();
            patient.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPatientActionPerformed
        String firstname = txtRegFirstname.getText();
        String lastname = txtRegLastname.getText();
        String idStr = txtRegId.getText();
        boolean gender = (cmbRegGender.getSelectedIndex() == 2); // true=Male, false=Female
        String birth = txtRegBirthdate.getText();
        String address = txtRegAddress.getText();
        String phone = txtRegPhone.getText();
        String email = txtRegEmail.getText();
        String username = txtRegUsername.getText();
        String password = txtRegPassword.getText();
        String comPassword = txtRegConfirmPass.getText();
        
        Response response = patientController.registerPatient(
            idStr, username, firstname, lastname,
            password, comPassword, email, birth, gender, phone, address
        );
        
        if (response.getStatus() == Status.OK) {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
            // Clear fields
            txtRegFirstname.setText(""); txtRegLastname.setText(""); txtRegId.setText("");
            txtRegPhone.setText(""); txtRegEmail.setText(""); txtRegUsername.setText("");
            txtRegPassword.setText(""); txtRegConfirmPass.setText(""); txtRegAddress.setText("");
            txtRegBirthdate.setText(""); cmbRegGender.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterPatientActionPerformed

    private void txtRegConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegConfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegConfirmPassActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegisterPatient;
    private javax.swing.JComboBox<String> cmbRegGender;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblRegUser;
    private javax.swing.JLabel lblRegPassword;
    private javax.swing.JLabel lblRegConfirmPass;
    private javax.swing.JLabel lblRegAddress;
    private javax.swing.JLabel lblRegBirthdate;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblRegFirstname;
    private javax.swing.JLabel lblRegLastname;
    private javax.swing.JLabel lblRegId;
    private javax.swing.JLabel lblRegGender;
    private javax.swing.JLabel lblRegPhone;
    private javax.swing.JLabel lblRegEmail;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JTabbedPane tabsMain;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JTextField txtRegConfirmPass;
    private javax.swing.JTextField txtRegAddress;
    private javax.swing.JTextField txtRegBirthdate;
    private javax.swing.JTextField txtLoginPassword;
    private javax.swing.JTextField txtRegFirstname;
    private javax.swing.JTextField txtRegLastname;
    private javax.swing.JTextField txtRegId;
    private javax.swing.JTextField txtRegPhone;
    private javax.swing.JTextField txtRegEmail;
    private javax.swing.JTextField txtRegUsername;
    private javax.swing.JTextField txtRegPassword;
    private core.view.PanelRound panelRound1;
    private core.view.PanelRound panelRound2;
    private core.view.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}


